# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu_createdoc.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuCreatedoc(HttpRunner):
    config = Config("testcase description").verify(False).base_url("https://${host}").variables(
        **{
            "host": "mubu.com",
            "phone": "18210850325",
            "password": "qweqaz123"
        })

    teststeps = [
        Step(
            RunRequest("/login/password")
                .get("/login/password")
                .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "_gat": "1",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "SLARDAR_WEB_ID": "f8be10eb-554b-4870-8784-826e31152735",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722718",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
                .post("/api/login/submit")
                .with_headers(
                **{
                    "content-length": "50",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "SLARDAR_WEB_ID": "385671c5-f92d-4896-bf7d-48d2c0d09c67",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722742",
                }
            )
                .with_data(
                {"phone": "$phone", "password": "$password", "remember": "true"}
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/list")
                .get("/list")
                .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "SLARDAR_WEB_ID": "385671c5-f92d-4896-bf7d-48d2c0d09c67",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722742",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MDc4NCIsImV4cCI6MTYwMDMxNDc4NCwiaWF0IjoxNTk3NzIyNzg0fQ.Orak-KTvp3h8B7kWQAE-lm43_lm9evf-HX6JI_TRGrFHRqHXhqLlJjSbmn23B_561OIzWwwkdKftLVWnQAyUYw",
                    "user_persistence": "95baaf68-45e3-4984-a11e-f190b408ff0d",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
                .post("/api/list/tip_new_update")
                .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722742",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MDc4NCIsImV4cCI6MTYwMDMxNDc4NCwiaWF0IjoxNTk3NzIyNzg0fQ.Orak-KTvp3h8B7kWQAE-lm43_lm9evf-HX6JI_TRGrFHRqHXhqLlJjSbmn23B_561OIzWwwkdKftLVWnQAyUYw",
                    "user_persistence": "95baaf68-45e3-4984-a11e-f190b408ff0d",
                    "SLARDAR_WEB_ID": "d7102f5f-950d-46de-b359-588cca16c3c5",
                }
            )
                .with_data("")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
                .post("/api/list/get")
                .with_headers(
                **{
                    "content-length": "38",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722742",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MDc4NCIsImV4cCI6MTYwMDMxNDc4NCwiaWF0IjoxNTk3NzIyNzg0fQ.Orak-KTvp3h8B7kWQAE-lm43_lm9evf-HX6JI_TRGrFHRqHXhqLlJjSbmn23B_561OIzWwwkdKftLVWnQAyUYw",
                    "user_persistence": "95baaf68-45e3-4984-a11e-f190b408ff0d",
                    "SLARDAR_WEB_ID": "d7102f5f-950d-46de-b359-588cca16c3c5",
                }
            )
                .with_data({"folderId": "0", "sort": "time", "keywords": "", "source": ""})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
                .assert_equal("body.data.folderId", "0")
                .assert_length_greater_than("body.data.documents", 5)
                # .assert_equal("body.data.documents[13].name", "demo")
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
                .post("/api/message/get_message_unread")
                .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722742",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MDc4NCIsImV4cCI6MTYwMDMxNDc4NCwiaWF0IjoxNTk3NzIyNzg0fQ.Orak-KTvp3h8B7kWQAE-lm43_lm9evf-HX6JI_TRGrFHRqHXhqLlJjSbmn23B_561OIzWwwkdKftLVWnQAyUYw",
                    "user_persistence": "95baaf68-45e3-4984-a11e-f190b408ff0d",
                    "SLARDAR_WEB_ID": "d7102f5f-950d-46de-b359-588cca16c3c5",
                }
            )
                .with_data("")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/create_doc")
                .post("/api/list/create_doc")
                .with_headers(
                **{
                    "content-length": "17",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MDc4NCIsImV4cCI6MTYwMDMxNDc4NCwiaWF0IjoxNTk3NzIyNzg0fQ.Orak-KTvp3h8B7kWQAE-lm43_lm9evf-HX6JI_TRGrFHRqHXhqLlJjSbmn23B_561OIzWwwkdKftLVWnQAyUYw",
                    "user_persistence": "95baaf68-45e3-4984-a11e-f190b408ff0d",
                    "SLARDAR_WEB_ID": "d7102f5f-950d-46de-b359-588cca16c3c5",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722785",
                }
            )
                .with_data({"folderId": "0", "type": "0"})
                .extract()
                .with_jmespath("body.data.id", "docid")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/doc$docid")
                .get("/doc$docid")
                .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MDc4NCIsImV4cCI6MTYwMDMxNDc4NCwiaWF0IjoxNTk3NzIyNzg0fQ.Orak-KTvp3h8B7kWQAE-lm43_lm9evf-HX6JI_TRGrFHRqHXhqLlJjSbmn23B_561OIzWwwkdKftLVWnQAyUYw",
                    "user_persistence": "95baaf68-45e3-4984-a11e-f190b408ff0d",
                    "SLARDAR_WEB_ID": "d7102f5f-950d-46de-b359-588cca16c3c5",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722785",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/list")
                .get("/list")
                .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/doc$docid",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MDc4NCIsImV4cCI6MTYwMDMxNDc4NCwiaWF0IjoxNTk3NzIyNzg0fQ.Orak-KTvp3h8B7kWQAE-lm43_lm9evf-HX6JI_TRGrFHRqHXhqLlJjSbmn23B_561OIzWwwkdKftLVWnQAyUYw",
                    "user_persistence": "95baaf68-45e3-4984-a11e-f190b408ff0d",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722785",
                    "SLARDAR_WEB_ID": "5f892971-3509-402b-aab9-419bceaef106",
                    "_gat_UA-77727571-3": "1",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
                .post("/api/list/tip_new_update")
                .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MDc4NCIsImV4cCI6MTYwMDMxNDc4NCwiaWF0IjoxNTk3NzIyNzg0fQ.Orak-KTvp3h8B7kWQAE-lm43_lm9evf-HX6JI_TRGrFHRqHXhqLlJjSbmn23B_561OIzWwwkdKftLVWnQAyUYw",
                    "user_persistence": "95baaf68-45e3-4984-a11e-f190b408ff0d",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722785",
                    "SLARDAR_WEB_ID": "5f892971-3509-402b-aab9-419bceaef106",
                    "_gat_UA-77727571-3": "1",
                }
            )
                .with_data("")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
                .post("/api/list/get")
                .with_headers(
                **{
                    "content-length": "38",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MDc4NCIsImV4cCI6MTYwMDMxNDc4NCwiaWF0IjoxNTk3NzIyNzg0fQ.Orak-KTvp3h8B7kWQAE-lm43_lm9evf-HX6JI_TRGrFHRqHXhqLlJjSbmn23B_561OIzWwwkdKftLVWnQAyUYw",
                    "user_persistence": "95baaf68-45e3-4984-a11e-f190b408ff0d",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722785",
                    "SLARDAR_WEB_ID": "5f892971-3509-402b-aab9-419bceaef106",
                    "_gat_UA-77727571-3": "1",
                }
            )
                .with_data({"folderId": "0", "sort": "time", "keywords": "", "source": ""})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
                .post("/api/message/get_message_unread")
                .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "99c7d6aa-3f52-4659-8697-652daa1de68f",
                    "_ga": "GA1.2.401798662.1595645152",
                    "mubu_inner": "1",
                    "s_v_web_id": "kdpshppv_hsboAKq9_G2uv_4SmO_9Ofp_J6Qv7NoTrTRS",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595645206,1597140962",
                    "_gid": "GA1.2.2095137028.1597673886",
                    "reg_entrance": "https%3A%2F%2F${host}%2Flist",
                    "csrf_token": "da7de617-b39c-41bf-9075-293eaab22f62",
                    "SESSION": "c874bb04-feb5-4a46-a2ed-a1b5d23472b8",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "18fb09a0-e106-11ea-8da7-8bef89673673",
                    "reg_prepareId": "173ffb1c70c-173ffb1c451-4143-beb4-4ae499255726",
                    "reg_focusId": "f84ae942-2750-4143-beb4-173ffb1ee23",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MDc4NCIsImV4cCI6MTYwMDMxNDc4NCwiaWF0IjoxNTk3NzIyNzg0fQ.Orak-KTvp3h8B7kWQAE-lm43_lm9evf-HX6JI_TRGrFHRqHXhqLlJjSbmn23B_561OIzWwwkdKftLVWnQAyUYw",
                    "user_persistence": "95baaf68-45e3-4984-a11e-f190b408ff0d",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1597722785",
                    "SLARDAR_WEB_ID": "5f892971-3509-402b-aab9-419bceaef106",
                    "_gat_UA-77727571-3": "1",
                }
            )
                .with_data("")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuCreatedoc().test_start()
